name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install canvas dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcairo2-dev libgif-dev libpango1.0-dev
    - run: cd "$GITHUB_WORKSPACE"/export-server && npm install
